##############################################################################
# java5.sh configuration file
##############################################################################
# NOTE: This file is automatically generated by puppet
# Changes to this file will be overwritten periodically by puppet!
##############################################################################

export JAVA_HOME=/opt/jdk5
export PATH=$JAVA_HOME/bin:$PATH

